###
GET http://localhost:9000/api/auth/jbetancur HTTP/1.1

###
GET http://localhost:9000/api_clientes?accesstoken=eyJhbGciOiJIUzI1NiJ9.amJldGFuY3Vy.7eIqVgwsnN46_jXXw0-sPG2pdnh6PLTZesiH7pTWvSM HTTP/1.1

###
GET http://localhost:9000/api_clientes?accesstoken=eyJhbGciOiJIUzI1NiJ9.amJldGFuY3Vy.7eIqVgwsnN46_jXXw0-sPG2pdnh6PLTZesiH7pTWvSM HTTP/1.1

###
POST http://localhost:9000/api_clientes?accesstoken=eyJhbGciOiJIUzI1NiJ9.amJldGFuY3Vy.7eIqVgwsnN46_jXXw0-sPG2pdnh6PLTZesiH7pTWvSM HTTP/1.1
Content-Type: application/json

{
        "cedula": 1000757693,
        "nombre": "Juan Pablo",
        "apellido": "Betancur",
        "direccion": "Carrera 48A # 84-34",
        "telefono": 2131266
    
}

###
DELETE http://localhost:9000/api_clientes/74?accesstoken=eyJhbGciOiJIUzI1NiJ9.amJldGFuY3Vy.7eIqVgwsnN46_jXXw0-sPG2pdnh6PLTZesiH7pTWvSM HTTP/1.1

###
PUT http://localhost:9000/api_clientes/24?accesstoken=eyJhbGciOiJIUzI1NiJ9.amJldGFuY3Vy.7eIqVgwsnN46_jXXw0-sPG2pdnh6PLTZesiH7pTWvSM HTTP/1.1
Content-Type: application/json

{
    "id": 13,
    "nombre": "Humilub",
    "descripcion": "Gotas lubricantes para los ojos",
    "dosis": 2
    
}
